name: Publish Debug Docker Hub image

on:
  push:
    branches: main

jobs:
  main-debug:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debug image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: deadsimpleauth/nginx:debug
          file: ./docker/Dockerfile-debug

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
